indexSuccess:
  metas:
    title: 'Spaced Repetition - Kanji Koohii'

reviewSuccess:
  metas:
    title: 'Flashcard Review'
  javascripts: [ /revtk/kanji-flashcardreview.juicy.js ]

summarySuccess:
  metas:
    title: 'Review Summary'
