indexSuccess:
  metas:
    title: 'Spaced Repetition - Kanji Koohii'
  stylesheets: [ '/revtk/study-base.juicy.css' ]

reviewSuccess:
  metas:
    title: 'Flashcard Review'
  stylesheets: [ /revtk/kanji-flashcardreview.juicy.css ]
  javascripts: [ /revtk/kanji-flashcardreview.juicy.js ]

summarySuccess:
  metas:
    title: 'Review Summary'
