version: '3'
services:

  web:

    build:
      context: ./docker/php-apache
      dockerfile: Dockerfile

    container_name: kk_webserver
    
    depends_on:
      - db

    image: kk_webserver_img  

    # 3000 Vite server
    ports:
      - "80:80"
      - "3000:3000"

    volumes:
      - ./src:/var/www/html

      # preserve bash history
      - ./docker/php-apache/bash/.bash_history:/root/.bash_history
  
  db:
    build:
      context: ./docker/db
    
    container_name: kk_mysql

    environment:
      MYSQL_DATABASE:      db_github
      MYSQL_USER:          koohii
      MYSQL_PASSWORD:      koohii
      MYSQL_ROOT_PASSWORD: root

    image: kk_mysql_img
    
    ports:
      - "3306:3306"

    restart: always
    
    volumes:
      - ./mysql56:/var/lib/mysql

      # use a custom prompt + aliases, preserve bash history
      - ./docker/db/bash/.bash_history:/root/.bash_history
      - ./docker/db/bash/.bashrc:/root/.bashrc
      
      # sources to initialize development database
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
