# recent posts partial included on the homepage (guest & member)
_recent:
  enabled:   true
  lifetime:  60*60*24   # one day

# news/index (/news/:year/:month )
index:
  enabled:   true
  lifetime:  60*60*24
