index:
  metas:
    title: 'Index'
  #stylesheets: [ '/revtk/kanji-flashcardreview.juicy.css' ]
  
shuffle1Success:
  metas:
    title: 'Vocab Shuffle'

  javascripts: [ '/revtk/labs-alpha-flashcardreview.juicy.js' ]

shuffle2Success:
  metas:
    title: 'Vocab Shuffle'

  javascripts: [ '/revtk/labs-alpha-flashcardreview.juicy.js' ]

all:
  metas:
    title: 'Labs'
