index:
  metas:
    title: 'Study: Introduction'
  
edit:
  metas:
    title: 'Index'
  
failedlist:
  metas:
    title: 'Study: Failed Kanji List'
  
mystories:
  metas:
    title: 'Study: My Stories List'
 
# FIXME : use study entry for study module  OR  use additional entry here?
# all:
#   javascripts: [ '/revtk/study-base.juicy.js' ]
