editSuccess:
  metas:
    title: "Study - Kanji Koohii"

failedlistSuccess:
  metas:
    title: "Restudy List - Kanji Koohii"

mystoriesSuccess:
  metas:
    title: "My Stories - Kanji Koohii"

all:
  metas:
    title: "Study - Kanji Koohii"

  javascripts:
    - src/entry-study.ts
