flashcardlistSuccess:
  metas:
    title: "Flashcard List - Kanji Koohii"

editkeywords:
  metas:
    title: "Edit Keywords - Kanji Koohii"

all:
  metas:
    title: "Manage Flashcards - Kanji Koohii"

  javascripts:
    - src/entry-manage.ts
