indexGuest:
  metas:
    title:  'Kanji Koohii'
  
  # reset the site-wide styles & scripts for the landing page
  #javascripts: [-*]
  #stylesheets: [-*]

loginSuccess:
  metas:
    title:  'Sign In - Kanji Koohii'
    robots: 'noindex, follow'
  
contactSuccess:
  metas:
    title:  'Contact - Kanji Koohii'
    robots: 'noindex, follow'

memberslistSuccess:
  metas:
    title:  'Who''s reviewing? - Kanji Koohii'
    robots: 'noindex, nofollow'

