# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~

test:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~

  mailer:
    param:
      delivery_strategy: none

dev:
  mailer:
    param:
      delivery_strategy: none

all:
  request:
    class: coreRequest

  # disable SwiftMailer initialization
  #  ( cf. https://github.com/FriendsOfSymfony1/symfony1/issues/244#issuecomment-825880023 )
  mailer:
    class: sfNoMailer

  response:
    class: coreWebResponse

  user:
    class: rtkUser
  #  param:
  #    timeout:         1800
  #   logging:         %SF_LOGGING_ENABLED%
  #   use_flash:       true
  #   default_culture: %SF_DEFAULT_CULTURE%

  storage:
    class: sfSessionStorage
    param:
      session_name: koohii

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true

  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true
