index:
  metas:
    title: 'Index'
  
shuffle1Success:
  metas:
    title: 'Vocab Shuffle'

  javascripts: [ '/revtk/labs-alpha-flashcardreview.juicy.js' ]

shuffle2Success:
  metas:
    title: 'Vocab Shuffle'

  javascripts: [ '/revtk/labs-alpha-flashcardreview.juicy.js' ]

all:
  metas:
    title: 'Labs'
