indexSuccess:
  metas:
    title: "Index"

shuffle1Success:
  metas:
    title: "Vocab Shuffle : Discover words made only of learned kanji"
  javascripts:
    - src/entry-review.ts

shuffle2Success:
  metas:
    title: "Vocab Shuffle : Discover words based on RTK index"
  javascripts:
    - src/entry-review.ts

all:
  metas:
    title: "Labs"
