extends: "stylelint-config-recommended-scss"

rules:
  block-no-empty: null
  no-descending-specificity: null
  no-empty-source: null
  scss/dollar-variable-pattern: "^--"
  scss/selector-no-redundant-nesting-selector: true
